### ISSUE TITLE
SliderLabel position doesn't update on game launch

### ISSUE THREAD

**Issue by VeryElusiveMoose** [KoBeWi/Godot-Slider-Label#2]
Using Godot 4.2.1

When placing a SliderLabel as a child of an HSlider, if the slider has a default value set that isn't zero, the Slider Label will not update its position until the slider is manually moved.

![image](https://github.com/KoBeWi/Godot-Slider-Label/assets/172297046/43324dc5-0c94-4584-a3f0-c36bb91fa5e9)

So far I have tested and confirmed this issue exists for HSliders, when the SliderLabel has Visibility Rule set to "Always".

![image](https://github.com/KoBeWi/Godot-Slider-Label/assets/172297046/9ad74a9e-559d-466a-aa6a-317707d2bf6f)

Video Demo:
https://github.com/KoBeWi/Godot-Slider-Label/assets/172297046/e5b03ef3-fe09-4da0-bcac-67c71464245d

Minimum Reproduction:
[Slider Label Min Rep.zip](https://github.com/user-attachments/files/15776330/Slider.Label.Min.Rep.zip)

_First time creating a github issue, so hopefully the attached file links work. I'm also not familiar with any community standards when it comes to issues or the minimum reproduction project, so please let me know if there is something I should do differently :)_

**Comment by KoBeWi** [comment]
Fixed by 21a2932b2f4dfb713837ac4b235e9aae381e946f

**Comment by VeryElusiveMoose** [comment]
Issue persists if the UI element starts not visible, when the UI element is made visible by some user input:

![image](https://github.com/KoBeWi/Godot-Slider-Label/assets/172297046/a5d4c60e-bd47-4918-8ce6-44864c4e0547)

Seems it could be fixed by adding call_deferred() to the update call in _notifications() - but I'm not super experienced with this so I'm not sure what other implications this might have.

Minimum Reproduction:
[Slider Label Min Rep 2.zip](https://github.com/user-attachments/files/15777009/Slider.Label.Min.Rep.2.zip)

**Comment by KoBeWi** [comment]
Fixed² by 48c787fe0b68da76f15409ab5dffcfab1f2f78f1
`call_deferred()` usually fixes all timing issues like that.
